### ISSUE TITLE
Improve yara3 plugin building

### ISSUE THREAD

**Issue by XVilka** [radareorg/radare2-extras#15]
Right now I'm calling this from the CI script. Preferably script should figure out some things by itself:

``` sh
r2_orig="$PWD"
if [ ! -d yara3.git ]; then
    git clone https://github.com/plusvic/yara.git yara3.git
    cd yara3.git
else
    cd yara3.git
    git clean -xdf
    git pull
fi
sh bootstrap.sh
NOSUDO=1 DESTDIR=/tmp/r2 PREFIX=/tmp/r2 PKG_CONFIG_PATH=/tmp/r2/lib/pkgconfig PATH=/tmp/valabind/bin:$PATH PYTHON_INSTALL_DIR=/tmp/r2 ./configure --prefix=${PREFIX} --libdir=${PREFIX}/lib
NOSUDO=1 DESTDIR=/tmp/r2 PREFIX=/tmp/r2 PKG_CONFIG_PATH=/tmp/r2/lib/pkgconfig PATH=/tmp/valabind/bin:$PATH PYTHON_INSTALL_DIR=/tmp/r2 make
NOSUDO=1 DESTDIR=/tmp/r2 PREFIX=/tmp/r2 PKG_CONFIG_PATH=/tmp/r2/lib/pkgconfig PATH=/tmp/valabind/bin:$PATH PYTHON_INSTALL_DIR=/tmp/r2 make install
cd "${r2_orig}/yara/yara3"
NOSUDO=1 DESTDIR=/tmp/r2 PREFIX=/tmp/r2 PKG_CONFIG_PATH=/tmp/r2/lib/pkgconfig LDFLAGS=-L/tmp/r2/lib CFLAGS=-I/tmp/r2/include PATH=/tmp/valabind/bin:$PATH PYTHON_INSTALL_DIR=/tmp/r2 ./configure --prefix=/tmp/r2 --libdir=/tmp/r2/lib
NOSUDO=1 DESTDIR=/tmp/r2 PREFIX=/tmp/r2 PKG_CONFIG_PATH=/tmp/r2/lib/pkgconfig LDFLAGS=-L/tmp/r2/lib CFLAGS=-I/tmp/r2/include PATH=/tmp/valabind/bin:$PATH PYTHON_INSTALL_DIR=/tmp/r2 make
NOSUDO=1 DESTDIR=/tmp/r2 PREFIX=/tmp/r2 PKG_CONFIG_PATH=/tmp/r2/lib/pkgconfig LDFLAGS=-L/tmp/r2/lib PATH=/tmp/valabind/bin:$PATH PYTHON_INSTALL_DIR=/tmp/r2 make install
```

**Comment by Bob131** [comment]
I thought I'd just leave a comment saying that the build fails to install on my system. It appears as though `R2PM_PLUGDIR` never gets set, and so `make install` attempts to install `core_yara3.so` to `/`

**Comment by radare** [comment]
Are u using latest r2 from git?

**Comment by Bob131** [comment]
I'm not, no, but yara3 is the only plugin giving me trouble in this 
regard.

**Comment by radare** [comment]
You should always use r2 from git. Or at least before complaining.

There have been many changes in r2pm and the yara plugin itself since 0.10.3

**Comment by Bob131** [comment]
Absolutely. But the fact remains that the current HEAD has the yara3 
makefile do operations on file paths that take the form of 
`$SOME_VARIABLE/whatever.asdf`, which is a well known method for 
causing Bad Things to happen. Combined with r2pm's `-gi` flag, it's the 
sort of thing that could prove disastrous.

I'm truly sorry if I've come off as demanding, my intention wasn't to 
'complain' per se; libyara support is totally irrelevant to my use 
case, it just seemed like a cool thing to play around with. I just 
wanted to give a heads up, since there was already a pending issue on 
the subject. Thanks for all your hard work.

**Comment by radare** [comment]
Can you send a pr?

**Comment by sylvainpelissier** [comment]
r2yara has its own repository now.
