### ISSUE TITLE
pyc RBinInfo .bits should depend on Python version

### ISSUE THREAD

**Issue by x0urc3** [radareorg/radare2-extras#230]
**Describe the issue**
Python <3.6 use two byte operand and Python >=3.6 use one byte operand. See PR #229 

**How to reproduce?**

**Expected behavior**

Change .bits to 16 or 8 depending on version

**Possible fix**
Change .bits based on Python version https://github.com/radareorg/radare2-extras/blob/ef5771f7ce61b326977ce32d7605789f5f1f7e15/libr/bin/p/bin_pyc.c#L48

**Screenshots**

**Additional context**

**Comment by FXTi** [comment]
The real problem is: how to know whether the code is <= 3.6 or not just from the code itself?
For example, `rasm2 -a pyc -d 740064018301010064005300`, which is an expected result.
Just from the commands, there's no extra information can be extracted from .pyc file. All we have is the bytecode, unless user specify python version from command line for `rasm2`. 
As for other disassemble situation with a .pyc file, extracting version from magic number is definitely necessary.

**Comment by FXTi** [comment]
https://github.com/radareorg/radare2-extras/pull/229#issuecomment-582885396
I think using `asm.cpu` is better. You can specify by `-c`, giving more clear interface to user.
